FROM node:10.23.1-alpine3.10

WORKDIR /app

COPY package.json /app

RUN npm install 
#&& npm install -g nodemon

COPY . .

EXPOSE 3333

#ENTRYPOINT [ "nodemon","--max-old-space-size=4096","server.js" ]
ENTRYPOINT [ "npm" ,"start","-s"]