apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-{{ .Release.Namespace }}-secret-registry"
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}